name: CodeDeployCI
on:
  push:
    branches:
      - code
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install
      - name: Set Github Name
        run: git config --global user.name "prudhvir3ddy" && git config --global user.email "prudhvireddy.m01@gmail.com"
      - name: Deploy to GH Pages
        run: |
          git config --global user.email "prudhvireddy.m01@gmail.com"
          git config --global user.name "prudhvir3ddy"
          git remote set-url origin https://8398641dfc51972e7a1c13cfdb05e8c776b9584e@github.com/prudhvir3ddy/prudhvireddy.git
      - name: Updating Domain
        run: echo "Update domain"
